# Start AeroSpace at login

start-at-login = true


# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true


# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature

accordion-padding = 300


# Possible values: tiles|accordion

default-root-container-layout = 'tiles'


# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation

default-root-container-orientation = 'horizontal'


# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []

#on-focused-monitor-changed = ['move-mouse monitor-lazy-center']


# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodness#disable-hide-app

automatically-unhide-macos-hidden-apps = true


# [[on-window-detected]]
# if.app-id = 'com.apple.systempreferences'
# if.app-name-regex-substring = 'settings'
# if.window-title-regex-substring = 'substring'
# if.workspace = 'workspace-name'
# if.during-aerospace-startup = true
# check-further-callbacks = true
# run = ['layout floating', 'move-node-to-workspace S']  # The callback itself

#[[on-window-detected]]
#if.app-name-regex-substring = 'finder'
#run = 'layout floating'


# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping

[key-mapping]
preset = 'qwerty'


# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors

[gaps]
inner.horizontal = 16
inner.vertical = 16
outer.left = 16
outer.bottom = 16
outer.top = 16
outer.right = 16


# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}

[mode.main.binding]

cmd-h = []     # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"


# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

ctrl-f4 = [
  'layout floating',
  'fullscreen on',
  'move-node-to-workspace Floating --focus-follows-window',
]
ctrl-f3 = [
  'layout tiling',
  'move-node-to-workspace Tiling --focus-follows-window',
  'balance-sizes',
]

f3 = 'focus left --ignore-floating'
f4 = 'focus right --ignore-floating'
f2 = 'focus down --ignore-floating'
f1 = 'focus up --ignore-floating'

cmd-f3 = 'move left'
cmd-f4 = 'move right'
cmd-f2 = 'move down'
cmd-f1 = 'move up'

alt-f3 = 'join-with left'
alt-f4 = 'join-with right'
alt-f2 = 'join-with up'
alt-f1 = 'join-with down'

shift-f4 = 'resize width +200'
shift-f3 = 'resize width -200'
shift-f1 = 'resize height +200'
shift-f2 = 'resize height -200'

#alt-tab = 'workspace-back-and-forth'
#alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

ctrl-alt-cmd-esc = 'mode service'
cmd-alt-ctrl-tab = 'flatten-workspace-tree'


# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']


[[on-window-detected]]
check-further-callbacks = true
run = 'move-node-to-workspace Floating --focus-follows-window'


[workspace-to-monitor-force-assignment]
#1 = '^Built-in.*$'
#2 = '^DELL U.*$'
#3 = '^DELL S.*$'
#     4 = '^dell$'
#     5 = 'main'
#     6 = '^elgato$'
