#after-startup-command = ['exec-and-forget sketchybar']

# Notify Sketchybar about workspace change
#exec-on-workspace-change = ['/bin/bash', '-c',
#  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
#  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=0'
#]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 300

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'vertical'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
#on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodness#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# [[on-window-detected]]
# if.app-id = 'com.apple.systempreferences'
# if.app-name-regex-substring = 'settings'
# if.window-title-regex-substring = 'substring'
# if.workspace = 'workspace-name'
# if.during-aerospace-startup = true
# check-further-callbacks = true
# run = ['layout floating', 'move-node-to-workspace S']  # The callback itself

#[[on-window-detected]]
#if.app-name-regex-substring = 'finder'
#run = 'layout floating'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 12
inner.vertical = 12
outer.left = 12
outer.bottom = 12
outer.top = 12
outer.right = 12

#[key-mapping.key-notation-to-key-code]
#unicorn = '"'

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

cmd-h = []     # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'ﬂﬂ
# '''


#cmd-alt-ctrl-q = 'layout floating'
#cmd-alt-ctrl-r = 'layout tiling'
#cmd-alt-ctrl-w = 'fullscreen on'
#cmd-alt-ctrl-e = 'fullscreen off'
#cmd-alt-ctrl-t = 'balance-sizes'

cmd-alt-ctrl-f4 = ['layout floating', 'fullscreen on']
cmd-alt-ctrl-f3 = ['layout tiling', 'balance-sizes']
cmd-alt-ctrl-n = 'flatten-workspace-tree'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
#alt-slash = 'layout tiles horizontal vertical'
#alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
f3 = 'focus left --ignore-floating'
f4 = 'focus right --ignore-floating'
f2 = 'focus down --ignore-floating'
f1 = 'focus up --ignore-floating'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
cmd-f3 = 'move left'
cmd-f4 = 'move right'
cmd-f2 = 'move down'
cmd-f1 = 'move up'

cmd-alt-f3 = 'join-with left'
cmd-alt-f4 = 'join-with right'
cmd-alt-f2 = 'join-with up'
cmd-alt-f1 = 'join-with down'


# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-f4 = 'resize width +200'
alt-f3 = 'resize width -200'
alt-f1 = 'resize height +200'
alt-f2 = 'resize height -200'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
#alt-1 = 'workspace 1'
#alt-2 = 'workspace 2'
#alt-3 = 'workspace 3'
#alt-4 = 'workspace 4'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
#alt-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
#alt-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
#alt-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
#alt-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'

#alt-tab = 'workspace-back-and-forth'
#alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
ctrl-alt-cmd-esc = 'mode service'
#ctrl-alt-cmd-a = 'mode apps'

# alt-t = 'exec-and-forget open -a /Applications/Telegram.app'
#alt-o = 'exec-and-forget open -a /Applications/Obsidian.app'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
#r = ['flatten-workspace-tree', 'mode main'] # reset layout
#f = [
#    'layout floating tiling',
#    'mode main',
#] # Toggle between floating and tiling layout
#backspace = ['close-all-windows-but-current', 'mode main']

[mode.apps.binding]
#alt-w = ['exec-and-forget open -a /Applications/WezTerm.app', 'mode main']

[workspace-to-monitor-force-assignment]
#1 = '^Built-in.*$'
#2 = '^DELL U.*$'
#3 = '^DELL S.*$'
#     4 = '^dell$'
#     5 = 'main'
#     6 = '^elgato$'
